Repository clapsheep/wardrobe, pull requests merged in 2024-06, with the labels that each got.

#3 [doc] README 및 PR 템플릿 생성
  PULL_REQUEST_TEMPLATE.md
  README.md
Labels: doc

#4 [doc] 이슈 템플릿 작성
  .github/ISSUE_TEMPLATE/기능개발-이슈-템플릿.md
Labels: doc

#48 [feat] MongoDB 연결 #47
  package-lock.json
  package.json
  src/app/api/users/[userId]/route.ts
  src/app/api/users/route.ts
  src/app/layout.tsx
  src/app/users/page.tsx
  src/lib/dbConnect.ts
  src/models/user.ts
  src/styles/globals.css
  src/types/DatabaseTypes.ts
  src/utils/api/fetch.ts
  src/utils/api/index.ts
  tailwind.config.ts
Labels: feat

#51 [chore] tailwind theme 추가
  tailwind.config.ts
Labels: chore

#56 [feat] 스키마생성 및 API 설계
  package-lock.json
  package.json
  src/app/api/product/[productId]/route.ts
  src/app/api/product/route.ts
  src/app/api/user/[userId]/dressroom/[productId]/route.ts
  src/app/api/user/[userId]/dressroom/route.ts
  src/app/api/user/[userId]/route.ts
  src/app/api/user/route.ts
  src/app/api/users/route.ts
  src/app/user/page.tsx
  src/lib/dbConnect.ts
  src/models/product.ts
  src/models/style.ts
  src/models/user.ts
  src/types/DatabaseTypes.ts
  src/utils/api/fetch.ts
Labels: feat
