Repository clapsheep/wardrobe, pull requests merged in 2024-07, with the labels that each got.

#57 [feat] 옷장 item 추가 관련 REST API 생성
  src/app/api/product/[productId]/route.ts
  src/app/api/product/route.ts
  src/app/api/style/[styleId]/route.ts
  src/app/api/style/route.ts
  src/app/api/user/[userId]/dressroom/[productId]/route.ts
  src/app/api/user/[userId]/dressroom/query/route.ts
  src/app/api/user/[userId]/dressroom/route.ts
  src/app/api/user/[userId]/route.ts
  src/app/api/user/[userId]/style/[styleId]/route.ts
  src/app/api/user/[userId]/style/bookmark/route.ts
  src/app/api/user/[userId]/style/recommand/route.ts
  src/app/api/user/[userId]/style/route.ts
  src/app/api/user/route.ts
  src/models/product.ts
  src/models/schema.ts
  src/models/style.ts
  src/models/user.ts
  src/types/DatabaseTypes.ts
Labels: feat

#58 [feat] bookmark REST api 설계
  middleware.ts
  package-lock.json
  package.json
  src/app/api/user/[userId]/auth/route.ts
  src/app/api/user/[userId]/bookmark/[styleId]/route.ts
  src/app/api/user/[userId]/bookmark/route.ts
  src/app/api/user/[userId]/like/[styleId]/route.ts
  src/app/api/user/[userId]/like/route.ts
  src/app/api/user/route.ts
Labels: feat

#60 Clapsheep/develop
  public/sprite.svg
  public/svg/_sprite.svg
  public/svg/add.svg
  public/svg/arrow-right.svg
  public/svg/bookmark_false.svg
  public/svg/bookmark_true.svg
  public/svg/burger.svg
  public/svg/cancel.svg
  public/svg/cancel_filled.svg
  public/svg/chevron-down.svg
  public/svg/filter.svg
  public/svg/gitHub.svg
  public/svg/link.svg
  public/svg/log-in.svg
  public/svg/log-out.svg
  public/svg/pencil.svg
  public/svg/person.svg
  public/svg/search.svg
  src/app/user/page.tsx
  src/components/atoms/BasicButton.tsx
  src/components/atoms/Svg.tsx
  src/components/atoms/Svg/Svg.tsx
  src/components/atoms/TagButton.tsx
  src/components/atoms/TagInput.tsx
  src/components/atoms/index.ts
  src/pages/_document.tsx
  tailwind.config.ts
Labels: feat

#61 [fix] Svg 수정으로 인한 Header 수정
  public/logo.svg
  public/svg/_sprite.svg
  public/svg/logo-mobile_Black.svg
  public/svg/logo-mobile_White.svg
  public/svg/logo-web_Black.svg
  public/svg/logo-web_White.svg
  src/components/atoms/Svg.tsx
  src/components/molecules/Header/Header.tsx
Labels: feat

#62 [fix] user 스키마 및 타입 수정
  src/models/schema.ts
  src/types/DatabaseTypes.ts
Labels: feat

#63 [feat] Main 페이지 캐러셀 구현 #30
  next.config.mjs
  package-lock.json
  package.json
  src/app/api/style/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/app/user/page.tsx
  src/components/molecules/MainCarousel.tsx
  src/components/molecules/index.ts
Labels: feat

#65 [feat] 메인 캐러셀 기능 추가 및 메인 페이지 마크업
  public/svg/_sprite.svg
  public/svg/arrow-up-right.svg
  src/app/page.tsx
  src/components/molecules/MainCarousel.tsx
  src/components/organism/RecommendStyleByItem.tsx
  src/components/organism/index.ts
Labels: markup, feat

#66 [feat] Main 페이지 추천 기능 구현 #31
  src/app/api/style/route.ts
  src/app/api/user/[userId]/route.ts
  src/app/api/user/[userId]/style/recommand/route.ts
  src/app/api/user/[userId]/style/recommend/route.ts
  src/app/layout.tsx
  src/app/page.tsx
  src/components/molecules/MainCarousel.tsx
  src/components/organism/RecommendStyleByItem.tsx
Labels: feat

#68 [feat] 메인페이지
  src/app/api/user/[userId]/style/recommend/route.ts
  src/app/dressroom/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/style/[productId]/page.tsx
  src/app/style/page.tsx
  src/components/organism/RecommendStyleByItem.tsx
Labels: feat

#69 [feat] sign in 마크업 #35
  public/svg/_sprite.svg
  public/svg/visibility_off.svg
  public/svg/visibility_on.svg
  src/app/login/page.tsx
  src/components/atoms/BasicButton.tsx
  src/components/atoms/BasicInput.tsx
  src/components/atoms/index.ts
Labels: markup, feat

#70 [Feat]로그인 및 메인 수정
  src/app/login/page.tsx
  src/app/page.tsx
  src/components/atoms/BasicButton.tsx
  src/components/atoms/BasicInput.tsx
  src/components/atoms/ResponsiveComponent.tsx
  src/components/molecules/MainCarousel.tsx
  src/components/molecules/index.ts
  src/components/organism/RecommendStyleByItemForDesktop.tsx
  src/components/organism/RecommendStyleByItemForMobile.tsx
  src/components/organism/index.ts
  src/utils/hooks/index.ts
  src/utils/hooks/useMediaQuery.ts
Labels: feat

#71 [feat] 유저 프로필 컴포넌트
  src/app/profile/[id]/page.tsx
  src/components/atoms/Profile/UserClothesStyleCount.tsx
  src/components/atoms/Profile/UserId.tsx
  src/components/atoms/Profile/UserImg.tsx
  src/components/atoms/Profile/UserInfo.tsx
  src/components/molecules/Profile/UserProfile.tsx
Labels: markup, feat

#73 [feat] 프로필 페이지 마크업
  public/svg/defaultProfile.svg
  src/app/profile/[id]/page.tsx
  src/components/atoms/Profile/UserId.tsx
  src/components/atoms/Profile/UserImg.tsx
  src/components/atoms/Profile/UserInfo.tsx
  src/components/atoms/Profile/UserName.tsx
  src/components/molecules/Profile/UserProfile.tsx
Labels: feat

#74 [refactor] 이미지 컴포넌트 priority 추가 및 BasicButton 컴포넌트 사용
  src/components/atoms/Profile/UserImg.tsx
  src/components/atoms/Profile/UserInfo.tsx
Labels: refactor

#76 [feat] sign in 기능 구현 #38, #38
  middleware.ts
  package-lock.json
  package.json
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/product/[productId]/route.ts
  src/app/api/product/route.ts
  src/app/api/style/[styleId]/route.ts
  src/app/api/style/route.ts
  src/app/api/user/[userId]/auth/route.ts
  src/app/api/user/[userId]/bookmark/[styleId]/route.ts
  src/app/api/user/[userId]/bookmark/route.ts
  src/app/api/user/[userId]/dressroom/[productId]/route.ts
  src/app/api/user/[userId]/dressroom/query/route.ts
  src/app/api/user/[userId]/dressroom/route.ts
  src/app/api/user/[userId]/like/[styleId]/route.ts
  src/app/api/user/[userId]/like/route.ts
  src/app/api/user/[userId]/route.ts
  src/app/api/user/[userId]/style/recommend/route.ts
  src/app/api/user/[userId]/style/route.ts
  src/app/api/user/route.ts
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/profile/[id]/page.tsx
  src/auth.ts
  src/components/atoms/ResponsiveComponent.tsx
  src/components/atoms/index.ts
  src/components/molecules/Header.tsx
  src/lib/api/fetch.ts
  src/lib/api/index.ts
  src/lib/hooks/index.ts
  src/lib/hooks/useMediaQuery.ts
  src/lib/models/schema.ts
  src/lib/utils/dbConnect.ts
  src/lib/utils/getUserFromDb.ts
  src/lib/utils/index.ts
  src/lib/utils/saltAndHashPassword.ts
Labels: feat
